name: HCPSecrets
on: workflow_dispatch
jobs:
  top-secret:
    runs-on: ubuntu-latest
    steps:
      - name: tell me a secret!
        run: echo "My secret is ${{ secrets.HARDCODEDSECRET }}"

      
