name: HCPVaultSecrets Access
on: push
jobs:
  top-secret:
    runs-on: ubuntu-latest
    steps:
      -name: Tell me a secret!
      run: echo "My existing secret is ${{ secrets.NEWSECRETSS }}"

      
