name: HCPVaultSecrets Access

on: 
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env: 

    steps:
      -name: Tell me a secret!
      run: echo "My existing secret is ${{ secrets.NEWSECRETSS }}"

      -name: Unset secret
      run: echo "My unknown secret is ${{ secrets.NOOOONEWSECRETSS }}"
